### ISSUE TITLE
Any plans to publish this image in Docker Hub?

### ISSUE THREAD

**Issue by x80486** [guessi/puppeteer-chrome#1]

**Comment by guessi** [comment]
@x80486 Actually, it did have an image repo on DockerHub but I removed it last week, where you can find history [in this commit](https://github.com/guessi/puppeteer-chrome/commit/c844446369d960b151663134ac6066822f969e15). If you are going to run puppeteer as container, you can still build it by yourself by executing [build.sh](https://github.com/guessi/puppeteer-chrome/blob/master/build.sh) and [run.sh](https://github.com/guessi/puppeteer-chrome/blob/master/run.sh).

**_Why I remove support for image releasing?_**

The reason is quite simple, both Chrome & Puppeteer releases became more and more frequently. I'm not going to provide a container image with vulnerabilities, but there are too many security fixes for Chrome nowadays. To maintain security fixes up-to-date became an annoying job to me. So I decided to turn this repo to be "sample script only" but not a container image source.

**Comment by x80486** [comment]
No problem, I was looking more for an image like `buildkite/puppeteer`, where they install `google-chrome-stable` and that provides all dependencies within the image, that's all.

**Comment by guessi** [comment]
@x80486 Thanks for understanding. Unfortunately [buildkite/docker-puppeteer](https://github.com/buildkite/docker-puppeteer) was [discontinued back in 2020-Q3](https://github.com/buildkite/docker-puppeteer/pull/164). To keep image containers up-to-date, I would suggest you to create an issue like this to puppeteer official directly, that would be relatively simple and most trustworthy for users.
